use_frameworks!

platform :ios, '9.0'

target 'MTCategoryComponent_Example' do
  pod 'MTCategoryComponent', :path => '../'

  target 'MTCategoryComponent_Tests' do
    inherit! :search_paths

    
  end
end
