use_frameworks!

platform :ios, '9.0'

target 'MTCategoryComponent_Example' do
  pod 'MTCategoryComponent', :path => '../'
  pod 'LookinServer', '1.0.2', :configurations => ['Debug']
  target 'MTCategoryComponent_Tests' do
    inherit! :search_paths

    
  end
end
